---
- name: Install and configure Ethereum Light Client
  hosts: all
  become: yes
  tasks:
    - name: Update and install dependencies
      apt:
        name:
          - software-properties-common
          - build-essential
          - git
          - curl
          - wget
        state: present
        update_cache: yes

    - name: Add Ethereum PPA
      apt_repository:
        repo: 'ppa:ethereum/ethereum'
        state: present

    - name: Install geth
      apt:
        name: geth
        state: present

    - name: Create systemd service for geth
      copy:
        dest: /etc/systemd/system/geth.service
        content: |
          [Unit]
          Description=Ethereum Go Client
          After=network.target

          [Service]
          Type=simple
          User=root
          ExecStart=/usr/bin/geth --syncmode light --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

    - name: Enable and start geth service
      systemd:
        name: geth
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
