---
- name: Setup Ethereum Light Client on Ubuntu EC2 Instance
  hosts: all
  become: yes
  vars:
    helios_network: "mainnet"
    helios_fall_back: "https://sync-mainnet.beaconcha.in"
    helios_consensus_rpc: "https://www.lightclientdata.org"
    helios_execution_rpc: "https://eth-mainnet.g.alchemy.com/v2/demo"
    helios_checkpoint: "0x60409a013161b33c8c68c6183c7753e779ec6c24be2f3c50c6036c30e13b34a6"
    helios_rpc_port: 8545
    helios_rpc_bind_ip: "0.0.0.0"
    helios_data_dir: "/var/lib/helios"
    helios_service_name: "helios"
    helios_binary_path: "/root/.helios/bin/helios"
    heliosup_path: "/root/.helios/bin/heliosup"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        force: yes

    - name: Install necessary packages
      apt:
        name:
          - curl
          - wget
          - unzip
        state: present

    - name: Run Helios installer script
      ansible.builtin.shell: "curl https://raw.githubusercontent.com/a16z/helios/master/heliosup/install | bash"
      args:
        executable: /bin/bash

    - name: Run Helios installation script using full path
      ansible.builtin.shell: "{{ heliosup_path }}"
      args:
        executable: /bin/bash

    - name: Verify Helios installation
      command: "{{ helios_binary_path }} --version"
      register: helios_version

    - name: Print Helios version
      debug:
        msg: "{{ helios_version.stdout }}"
      when: helios_version.rc == 0

    - name: Create data directory for Helios
      file:
        path: "{{ helios_data_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create systemd service file for Helios
      become: yes
      copy:
        dest: "/etc/systemd/system/{{ helios_service_name }}.service"
        content: |
          [Unit]
          Description=Helios Ethereum Light Client
          After=network.target

          [Service]
          Type=simple
          User=root
          WorkingDirectory={{ helios_data_dir }}
          ExecStart=sudo {{ helios_binary_path }} \
            --network {{ helios_network }} \
            --fallback {{ helios_fall_back }} \
            --consensus-rpc {{ helios_consensus_rpc }} \
            --execution-rpc {{ helios_execution_rpc }} \
            --checkpoint {{ helios_checkpoint }} \
            --rpc-port {{ helios_rpc_port }} \
            --rpc-bind-ip {{ helios_rpc_bind_ip }} \
            --data-dir {{ helios_data_dir }}
          Restart=on-failure
          RestartSec=10
          LimitNOFILE=4096

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Helios service
      systemd:
        name: "{{ helios_service_name }}"
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
